/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoranRouteImport } from './routes/coran'
import { Route as DevenirProfesseurRouteImport } from './routes/devenir-professeur'
import { Route as ProfesseursRouteImport } from './routes/professeurs'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedMemorisationRouteImport } from './routes/_authenticated/memorisation'
import { Route as AuthenticatedMonDaharaRouteImport } from './routes/_authenticated/mon-dahara'
import { Route as AuthenticatedPrieresRouteImport } from './routes/_authenticated/prieres'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as BibliothequeSlugRouteImport } from './routes/bibliotheque.$slug'
import { Route as ProfesseursSlugRouteImport } from './routes/professeurs.$slug'
import { Route as AuthenticatedClasseIdRouteImport } from './routes/_authenticated/classe.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoranRoute = CoranRouteImport.update({
  id: '/coran',
  path: '/coran',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirProfesseurRoute = DevenirProfesseurRouteImport.update({
  id: '/devenir-professeur',
  path: '/devenir-professeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursRoute = ProfesseursRouteImport.update({
  id: '/professeurs',
  path: '/professeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemorisationRoute =
  AuthenticatedMemorisationRouteImport.update({
    id: '/memorisation',
    path: '/memorisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonDaharaRoute = AuthenticatedMonDaharaRouteImport.update({
  id: '/mon-dahara',
  path: '/mon-dahara',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrieresRoute = AuthenticatedPrieresRouteImport.update({
  id: '/prieres',
  path: '/prieres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BibliothequeSlugRoute = BibliothequeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BibliothequeRoute,
} as any)
const ProfesseursSlugRoute = ProfesseursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProfesseursRoute,
} as any)
const AuthenticatedClasseIdRoute = AuthenticatedClasseIdRouteImport.update({
  id: '/classe/$id',
  path: '/classe/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/bibliotheque': typeof BibliothequeRouteWithChildren
  '/contact': typeof ContactRoute
  '/coran': typeof CoranRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/professeurs': typeof ProfesseursRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/memorisation': typeof AuthenticatedMemorisationRoute
  '/mon-dahara': typeof AuthenticatedMonDaharaRoute
  '/prieres': typeof AuthenticatedPrieresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/bibliotheque/$slug': typeof BibliothequeSlugRoute
  '/professeurs/$slug': typeof ProfesseursSlugRoute
  '/classe/$id': typeof AuthenticatedClasseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/bibliotheque': typeof BibliothequeRouteWithChildren
  '/contact': typeof ContactRoute
  '/coran': typeof CoranRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/professeurs': typeof ProfesseursRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/memorisation': typeof AuthenticatedMemorisationRoute
  '/mon-dahara': typeof AuthenticatedMonDaharaRoute
  '/prieres': typeof AuthenticatedPrieresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/bibliotheque/$slug': typeof BibliothequeSlugRoute
  '/professeurs/$slug': typeof ProfesseursSlugRoute
  '/classe/$id': typeof AuthenticatedClasseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/bibliotheque': typeof BibliothequeRouteWithChildren
  '/contact': typeof ContactRoute
  '/coran': typeof CoranRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/professeurs': typeof ProfesseursRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/_authenticated/memorisation': typeof AuthenticatedMemorisationRoute
  '/_authenticated/mon-dahara': typeof AuthenticatedMonDaharaRoute
  '/_authenticated/prieres': typeof AuthenticatedPrieresRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/bibliotheque/$slug': typeof BibliothequeSlugRoute
  '/professeurs/$slug': typeof ProfesseursSlugRoute
  '/_authenticated/classe/$id': typeof AuthenticatedClasseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/bibliotheque'
    | '/contact'
    | '/coran'
    | '/devenir-professeur'
    | '/professeurs'
    | '/tarifs'
    | '/memorisation'
    | '/mon-dahara'
    | '/prieres'
    | '/profil'
    | '/reservations'
    | '/bibliotheque/$slug'
    | '/professeurs/$slug'
    | '/classe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/bibliotheque'
    | '/contact'
    | '/coran'
    | '/devenir-professeur'
    | '/professeurs'
    | '/tarifs'
    | '/memorisation'
    | '/mon-dahara'
    | '/prieres'
    | '/profil'
    | '/reservations'
    | '/bibliotheque/$slug'
    | '/professeurs/$slug'
    | '/classe/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/bibliotheque'
    | '/contact'
    | '/coran'
    | '/devenir-professeur'
    | '/professeurs'
    | '/tarifs'
    | '/_authenticated/memorisation'
    | '/_authenticated/mon-dahara'
    | '/_authenticated/prieres'
    | '/_authenticated/profil'
    | '/_authenticated/reservations'
    | '/bibliotheque/$slug'
    | '/professeurs/$slug'
    | '/_authenticated/classe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  BibliothequeRoute: typeof BibliothequeRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoranRoute: typeof CoranRoute
  DevenirProfesseurRoute: typeof DevenirProfesseurRoute
  ProfesseursRoute: typeof ProfesseursRouteWithChildren
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coran': {
      id: '/coran'
      path: '/coran'
      fullPath: '/coran'
      preLoaderRoute: typeof CoranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-professeur': {
      id: '/devenir-professeur'
      path: '/devenir-professeur'
      fullPath: '/devenir-professeur'
      preLoaderRoute: typeof DevenirProfesseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs': {
      id: '/professeurs'
      path: '/professeurs'
      fullPath: '/professeurs'
      preLoaderRoute: typeof ProfesseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/memorisation': {
      id: '/_authenticated/memorisation'
      path: '/memorisation'
      fullPath: '/memorisation'
      preLoaderRoute: typeof AuthenticatedMemorisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-dahara': {
      id: '/_authenticated/mon-dahara'
      path: '/mon-dahara'
      fullPath: '/mon-dahara'
      preLoaderRoute: typeof AuthenticatedMonDaharaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prieres': {
      id: '/_authenticated/prieres'
      path: '/prieres'
      fullPath: '/prieres'
      preLoaderRoute: typeof AuthenticatedPrieresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/bibliotheque/$slug': {
      id: '/bibliotheque/$slug'
      path: '/$slug'
      fullPath: '/bibliotheque/$slug'
      preLoaderRoute: typeof BibliothequeSlugRouteImport
      parentRoute: typeof BibliothequeRoute
    }
    '/professeurs/$slug': {
      id: '/professeurs/$slug'
      path: '/$slug'
      fullPath: '/professeurs/$slug'
      preLoaderRoute: typeof ProfesseursSlugRouteImport
      parentRoute: typeof ProfesseursRoute
    }
    '/_authenticated/classe/$id': {
      id: '/_authenticated/classe/$id'
      path: '/classe/$id'
      fullPath: '/classe/$id'
      preLoaderRoute: typeof AuthenticatedClasseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMemorisationRoute: typeof AuthenticatedMemorisationRoute
  AuthenticatedMonDaharaRoute: typeof AuthenticatedMonDaharaRoute
  AuthenticatedPrieresRoute: typeof AuthenticatedPrieresRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedClasseIdRoute: typeof AuthenticatedClasseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMemorisationRoute: AuthenticatedMemorisationRoute,
  AuthenticatedMonDaharaRoute: AuthenticatedMonDaharaRoute,
  AuthenticatedPrieresRoute: AuthenticatedPrieresRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedClasseIdRoute: AuthenticatedClasseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BibliothequeRouteChildren {
  BibliothequeSlugRoute: typeof BibliothequeSlugRoute
}

const BibliothequeRouteChildren: BibliothequeRouteChildren = {
  BibliothequeSlugRoute: BibliothequeSlugRoute,
}

const BibliothequeRouteWithChildren = BibliothequeRoute._addFileChildren(
  BibliothequeRouteChildren,
)

interface ProfesseursRouteChildren {
  ProfesseursSlugRoute: typeof ProfesseursSlugRoute
}

const ProfesseursRouteChildren: ProfesseursRouteChildren = {
  ProfesseursSlugRoute: ProfesseursSlugRoute,
}

const ProfesseursRouteWithChildren = ProfesseursRoute._addFileChildren(
  ProfesseursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  BibliothequeRoute: BibliothequeRouteWithChildren,
  ContactRoute: ContactRoute,
  CoranRoute: CoranRoute,
  DevenirProfesseurRoute: DevenirProfesseurRoute,
  ProfesseursRoute: ProfesseursRouteWithChildren,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
